FROM p4lang/p4runtime-sh:latest

SHELL ["/bin/bash", "-c"]

WORKDIR /p4runtime-sh/

ENV PKG_DEPS git python3-venv

# git is required for codecov
RUN apt-get update && \
    apt-get install -y --no-install-recommends $PKG_DEPS && \
    rm -rf /var/cache/apt/* /var/lib/apt/lists/*

COPY . /p4runtime-sh
RUN source $VENV/bin/activate && \
    pip3 install --upgrade pip && \
    pip3 install --upgrade setuptools && \
    pip3 install -r requirements-dev.txt && \
    rm -rf ~/.cache/pip

ENTRYPOINT []
