FROM p4lang/p4runtime-sh:latest

SHELL ["/bin/bash", "-c"]

WORKDIR /p4runtime-sh/

RUN source $VENV/bin/activate && \
    pip3 install -r requirements-dev.txt && \
    rm -rf ~/.cache/pip

ENTRYPOINT []
