name: Test
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub if needed
      if: ${{ github.repository == 'p4lang/p4runtime-shell' && github.event_name == 'push' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and export p4lang/p4runtime-sh to Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: p4lang/p4runtime-sh,p4lang/p4runtime-sh:ci-${{ github.sha }}
        outputs: type=image
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build and export p4lang/p4runtime-sh-dev to Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.dev
        build-args: TAG=ci-${{ github.sha }} # ensures that we don't pull from Dockerhub first
        load: true
        tags: p4lang/p4runtime-sh-dev
        cache-from: |
          p4lang/p4runtime-sh:ci-${{ github.sha }}
          type=gha
        cache-to: type=gha,mode=max
    - name: Check Python code formatting
      run: docker run p4lang/p4runtime-sh-dev bash -c "source venv/bin/activate && flake8 p4runtime_sh config_builders"
    - name: Run unit tests and upload code coverage
      run: |
        ci_env=`bash <(curl -s https://codecov.io/env)`
        docker run $ci_env p4lang/p4runtime-sh-dev bash -c "source venv/bin/activate && nose2 --with-coverage p4runtime_sh config_builders && codecov"
    - name: Build and push p4lang/p4runtime-sh to Docker if needed
      if: ${{ github.repository == 'p4lang/p4runtime-shell' && github.event_name == 'push' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: p4lang/p4runtime-sh
