name: TOC
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v2
    - name: Update TOCs
      run: make toc
    - name: Check for changes
      run: |
        [ -z "$(git status --untracked-files=no --porcelain)" ]
